config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  default_url_options host: "https://ezgamble.herokuapp.com/"
  devise_for :users
  HighVoltage.configure do |config|
    config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  HighVoltage.configure do |config|
    config.home_page = 'index'  
  end
  
  resources :sites do
    member do
      get 'rating'
    end
  end
  
  resources :reviews
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    can [:destroy ], Review, user_id: user.id
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sites
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :site_id
end

app/models/performance.rb
class Performance < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :site_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :site
  
  validates_presence_of :title
  validates_presence_of :content
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :category
  has_many :features
  has_many :performances
  has_many :trusts
  has_many :reviews
    
  has_attached_file :preview, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :preview, content_type: /\Aimage\/.*\z/,
  default_url: ActionController::Base.helpers.asset_path("missing_site.jpg")
  
  validates_presence_of :title
  validates_presence_of :link
  validates_presence_of :preview
  validates_presence_of :description
  validates :description, length: { minimum: 90 }
  
  def get_site_avg_rating(site)
    trusts = site.trusts.average(:rating).to_i
    performances = site.performances.average(:rating).to_i
    features = site.features.average(:rating).to_i
    
    result = ( ( features + performances + trusts ) / 3 ).to_i
  end
end

app/models/trust.rb
class Trust < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :site_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :reviews
  
  validates_presence_of :username
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/,
  default_url: ActionController::Base.helpers.asset_path("missing.jpg")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:username, :email, :password, :password_confirmation, :image)}
      devise_parameter_sanitizer.permit(:sign_in){|u| u.permit(:email, :password, :remember_me)}
      devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:username, :email, :password, :current_password, :image)}
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:destroy]
  
  def create
    @user = current_user
    @review =  @user.reviews.build(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to site_path(params[:review][:site_id]), :notice => "Your Review has been Recorded. " }
        format.js
      else
        format.html { render :new }
        format.js
      end
     end
  end
  
  def destroy
    authorize! :destroy, @review
    respond_to do |format|
      if @review.destroy
        format.html { redirect_to sites_path, notice: 'Review is deleted Successfully.' }
        format.js
      else
        format.html { redirect_to sites_path, alert: 'Some Problem Occured.' }
        format.js
      end
    end
  end
  
  private
  
    def review_params
      params.require(:review).permit(:title, :content, :user_id, :site_id)
    end
    
    def set_review
      @review = Review.find(params[:id])
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.includes(:category).all.page(params[:page]).per(3)
  end

  def show
    @site = Site.includes(:category, :reviews).find(params[:id])
    if user_signed_in?
      @trust_rating = Trust.where(user_id: current_user.id, site_id: params[:id]).pluck(:rating)[0]
      if !@trust_rating.present? 
        @trust_rating = 0
      end
      
      @performance_rating = Performance.where(user_id: current_user.id, site_id: params[:id]).pluck(:rating)[0]
      if !@performance_rating.present? 
        @performance_rating = 0
      end
      
      @feature_rating = Feature.where(user_id: current_user.id, site_id: params[:id]).pluck(:rating)[0]
      if !@feature_rating.present? 
        @feature_rating = 0
      end
    end
    
    @result = @site.rating
    @review = Review.new
  end
  
  def rating
    if params[:type] == 'trust'
      @rating = Trust.create(rating: params[:star], site_id: params[:id], user_id: current_user.id)
    elsif params[:type] == 'performance'
      @rating = Performance.create(rating: params[:star], site_id: params[:id], user_id: current_user.id)
    else
      params[:type] == 'feature'
      @rating = Feature.create(rating: params[:star], site_id: params[:id], user_id: current_user.id)
    end
    
    if @rating.save
      redirect_to site_path(params[:id]), notice: 'Rating is successfully made.'
    else
      redirect_to site_path(params[:id]), alert: 'You can give rating only once per type.'
    end
    
    @site = Site.find(params[:id])
    @result = @site.get_site_avg_rating(@site)
    @site.update(rating: @result)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def resource_name
  #   :user
  # end
 
  # def resource
  #   @resource ||= User.new
  # end

  # def resource_class
  #   User
  # end
 
  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:user]
  # end
  
  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  
  # def user_signed_in?
  #   session[:user_id].present?
  # end
  def bootstrap_class_for(flash_type)
   case flash_type.to_sym
     when :success
       "alert-success"
     when :error
       "alert-danger"
     when :alert
       "alert-danger"
     when :notice
       "alert-success"
     when :warning
       "alert-warning"
     else
       flash_type.to_s
   end
 end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg, style: 'color: red') }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_footer.html.erb
<!-- Footer
</div>
================================================== -->
<footer id="footer" class="footer">

  <!-- Footer Widgets -->
  <div class="footer-widgets">
    <div class="footer-widgets__inner">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-3">
            <div class="footer-col-inner">

              <!-- Footer Logo -->
              <div class="footer-logo">
                <a href="<%= page_path('index') %>"><%= image_tag "images/logo.png", class: 'footer-logo__img' %></a>
              </div>
              <!-- Footer Logo / End -->

            </div>
          </div>
          <div class="col-sm-9 col-md-9">
            <div class="footer-col-inner">
              <!-- Widget: Contact Info -->
              <div class="widget widget--footer widget-contact-info">
                <h4 class="widget__title">Contact Info</h4>
                <div class="widget__content">
                  <div class="widget-contact-info__desc">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisi nel elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                  </div>
                  <div class="widget-contact-info__body info-block">
                    <div class="info-block__item">
                      <svg role="img" class="df-icon df-icon--basketball">
                        <use xlink:href=""/>
                      </svg>
                      <h6 class="info-block__heading">Contact Us</h6>
                      <a class="info-block__link" href="mailto:info@alchemists.com">info@alchemists.com</a>
                    </div>
                    <div class="info-block__item">
                      <svg role="img" class="df-icon df-icon--jersey">
                        <use xlink:href=""/>
                      </svg>
                      <h6 class="info-block__heading">Join Our Team!</h6>
                      <a class="info-block__link" href="mailto:tryouts@alchemists.com">tryouts@alchemists.com</a>
                    </div>
                    <div class="info-block__item info-block__item--nopadding">
                      <ul class="social-links">
                        <li class="social-links__item">
                          <a href="#" class="social-links__link"><i class="fa fa-facebook"></i> Facebook</a>
                        </li>
                        <li class="social-links__item">
                          <a href="#" class="social-links__link"><i class="fa fa-twitter"></i> Twitter</a>
                        </li>
                        <li class="social-links__item">
                          <a href="#" class="social-links__link"><i class="fa fa-google-plus"></i> Google+</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Widget: Contact Info / End -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer Widgets / End -->

  <!-- Footer Secondary -->
  <div class="footer-secondary footer-secondary--has-decor">
    <div class="container">
      <div class="footer-secondary__inner">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <ul class="footer-nav">
              <li class="footer-nav__item"><a href="<%= page_path('index') %>">Home</a></li>
              <li class="footer-nav__item"><a href="<%= sites_path %>">Sites</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer Secondary / End -->
</footer>
<!-- Footer / End -->

app/views/application/_header.html.erb
<div class="header-mobile clearfix" id="header-mobile">
  <div class="header-mobile__logo">
    <a href="<%= page_path('index') %>">
    <%= image_tag "images/logo.png", class: 'header-mobile__logo-img' %> </a>
  </div>
  <div class="header-mobile__inner">
    <a id="header-mobile__toggle" class="burger-menu-icon"><span class="burger-menu-icon__line"></span></a>
    <span class="header-mobile__search-icon" id="header-mobile__search-icon"></span>
  </div>
</div>

<!-- Header Desktop -->
<header class="header">

  <!-- Header Top Bar -->
  <div class="header__top-bar clearfix">
    <div class="container">

      <!-- Account Navigation -->
      <ul class="nav-account">
        <% if !user_signed_in? %>
          <li class="nav-account__item"><a href="<%= new_user_session_path %>">Login / Register</a></li>
        <% else %>
          <% if current_user.image.url.split('/')[-1] == "missing.png" %>
            <li class="nav-account__item"> <%= image_tag 'images/samples/avatar-empty.png', class: 'img-circle', style: 'width: 40px' %> </li>
          <% else %>
            <li class="nav-account__item"> <%= image_tag current_user.image.url(:thumb), class: 'img-circle', style: 'width: 40px' %> </li>
          <% end %>
          <li class="nav-account__item"> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
          <li class="nav-account__item"> <%= link_to current_user.username, edit_user_registration_path %> (Go to Profile) </li>
        <% end %>
        
      </ul>
      <!-- Account Navigation / End -->

    </div>
  </div>
  <!-- Header Top Bar / End -->

  <!-- Header Secondary -->
  <div class="header__secondary">
    <div class="container">
      <!-- Header Search Form -->
      <!-- <div class="header-search-form">
        <form action="#" id="mobile-search-form" class="search-form">
          <input type="text" class="form-control header-mobile__search-control" value="" placeholder="Enter your seach here...">
          <button type="submit" class="header-mobile__search-submit"><i class="fa fa-search"></i></button>
        </form>
      </div> -->
      <!-- Header Search Form / End -->
      <ul class="info-block info-block--header">
        <li class="info-block__item info-block__item--contact-primary">
          <svg role="img" class="df-icon df-icon--jersey">
            <use xlink:href=""/>
          </svg> 
          <h6 class="info-block__heading">Join Our Team!</h6>
          <a class="info-block__link" href="mailto:tryouts@alchemists.com">tryouts@alchemists.com</a>
        </li>
        <li class="info-block__item info-block__item--contact-secondary">
          <svg role="img" class="df-icon df-icon--basketball">
            <use xlink:href=""/>
          </svg> 
          <h6 class="info-block__heading">Contact Us</h6>
          <a class="info-block__link" href="mailto:info@alchemists.com">info@alchemists.com</a>
        </li>
      </ul>
    </div>
  </div>
  <!-- Header Secondary / End -->

  <!-- Header Primary -->
  <div class="header__primary">
    <div class="container">
      <div class="header__primary-inner">
        <!-- Header Logo -->
        <div class="header-logo">
          <a href="<%= page_path('index') %>"><%= image_tag "images/logo.png", class: "header-logo__img" %></a>
        </div>
        <!-- Header Logo / End -->

        <!-- Main Navigation -->
        <nav class="main-nav clearfix">
          <ul class="main-nav__list">
            <li> <a href="<%= page_path('index') %>">Home</a> </li>
            <li> <a href="<%= sites_path %>">Sites</a> </li>
          </ul>

          <!-- Social Links -->
          <!-- <ul class="social-links social-links--inline social-links--main-nav">
            <li class="social-links__item">
              <a href="#" class="social-links__link" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="social-links__item">
              <a href="#" class="social-links__link" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="social-links__item">
              <a href="#" class="social-links__link" data-toggle="tooltip" data-placement="bottom" title="Google+"><i class="fa fa-google-plus"></i></a>
            </li>
          </ul> -->
          <!-- Social Links / End -->

          <!-- Pushy Panel Toggle -->
          <a href="#" class="pushy-panel__toggle">
            <span class="pushy-panel__line"></span>
          </a>
          <!-- Pushy Panel Toggle / Eng -->
        </nav>
        <!-- Main Navigation / End -->
      </div>
    </div>
  </div>
  <!-- Header Primary / End -->

</header>

app/views/application/_notifications.html.erb
<div id="messages" class="">
 <% flash.each_with_index do |(k,v),i| %>
   <% next if k.to_s == 'timedout' %>
   <div id="message-<%= i %>" class="actual-message" style="margin-bottom: -1.5%;">
     <div class="alert <%= bootstrap_class_for(k.to_s.sub('_stay', '')) %>">
       <% if v.is_a?(Array) %>
         <ul style="color: black !important">
           <% v.each do |vv| %>
             <li style="color: black !important"><%= vv %></li>
           <% end %>
         </ul>
       <% else %>
         <p style="color: black !important"> <%= raw v %> </p>
       <% end %>
     </div>
   </div>
 <% end %>
</div>

<script type="text/javascript">
 window.setTimeout(function()
 {
   $("#messages").fadeTo(500, 0).slideUp(300, function()
   {
     $(this).remove();
   });
 }, 6000);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The AlChemists</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="template-basketball">
    <div class="site-wrapper clearfix">
      <div class="site-overlay"></div>
      
      <%= render "notifications" %>
      
      <%= render 'header' %>
      
      <%= render 'pushy_panel' %>
      
      <!-- <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->
      
      <%= yield %>
      
      <%= render 'footer' %>
      
    </div>
  </body>
  
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review, input_html: { class: 'reviews-form' }, remote: true do |f| %>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.input :title, label_html: { class: 'control-label' }, 
        input_html: { class: 'form-control' } %>
      </div>
      
      <div class="form-group">
        <%= f.input :content, label_html: { class: 'control-label' }, class: 'form-control', input_html: { rows: 5 }, as: :text %>
      </div>
      
      <%= f.hidden_field :site_id, value: @site.id %>
      
      <div class="form-group form-group--submit">
        <%= f.button :submit, class: 'btn btn-default btn-block btn-lg' %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<li class="comments__item" id="review_row_<%= review.id %>">
  <div class="comments__inner">
    <header class="comment__header">
      <div class="comment__author">
        <figure class="comment__author-avatar">
          <% if review.user.image.url.split('/')[-1] == "missing.png" %>
            <%= image_tag 'images/samples/avatar-empty.png' %>
          <% else %>
            <%= image_tag review.user.image.url(:thumb) %>
          <% end %>
        </figure>
        <div class="comment__author-info">
          <h5 class="comment__author-name"><%= review.user.username %></h5>
          <time class="comment__post-date" datetime="2016-08-23"><%= time_ago_in_words( review.created_at ) %> ago</time>
        </div>
      </div>
    </header>
    <div class="comment__body">
      <h4 class="comment__title"> <%= review.title %> </h4>
      <p style="color: grey;"> <%= review.content %> </p>
      <% if can? :destroy, review %>
        <p style="color: black"> <%= link_to 'Delete', review, method: :delete, remote: true %> </p>
      <% end %>
    </div>
  </div> <hr style="margin-top: 0px !important">
</li> 

app/views/reviews/create.js.erb
$("#reviews").append("<%= j render @review %>")
$("#review_row_<%= @review.id %>").hide().fadeIn(500)
$("#success-note").html("Your review is Recorded Successfully.")
$("#success-note").fadeOut(3000, function(){
  $(this).remove()
})
$("#review_title").val("")
$("#review_content").val("")
var count = $("#reviews-count").html()
$("#reviews-count").html(parseInt(count) + 1)
$("#top-reviews-count").html(parseInt(count) + 1)

app/views/reviews/destroy.js.erb
$("#review_row_<%= @review.id %>").fadeOut(600, function(){
  $(this).remove()
})
var count = $("#reviews-count").html()
$("#reviews-count").html(parseInt(count) - 1)
$("#top-reviews-count").html(parseInt(count) - 1)

app/views/sites/_site.html.erb
<!-- One Product Template  -->
<li class="product__item product__item--color-1 card">

  <div class="">
    <div class="product__img-holder">
      <a href="<%= site_path(site) %>"> <%= image_tag site.preview.url(:medium), style: 'height: 300px' %> </a>
    </div>
  </div>

  <div class="product__content card__content">

    <header class="product__header">
      <div class="product__header-inner">
        <span class="product__category"> <%= site.category.title %> </span>
        <h2 class="product__title"><a href="<%= site_path(site) %>"> <%= site.title %> </a></h2>
        <div class="product__ratings">
          <% site.rating.times do %>
            <i class="fa fa-star"></i>
          <% end %>
          <% (5 - site.rating).times do %>
            <i class="fa fa-star empty"></i>
          <% end %>
        </div>
      </div>
    </header>

    <div class="product__excerpt">
      <%= truncate(site.description, length: 90) %>
    </div>

    <footer class="product__footer">
      <!-- <a href="#" class="btn btn-default btn-single-icon product__wish"><i class="icon-heart"></i></a> -->
      <a href="<%= site_path(site) %>" class="btn btn-default btn-single-icon product__view"><i class="icon-eye"></i></a>
    </footer>
  </div>
</li>
<!-- One Product Template / End -->

app/views/sites/show.html.erb
<!-- Content
================================================== -->
<div class="site-content">
  <div class="container">

    <!-- Single Product -->
    <div class="products products--list products--list-lg">

      <div class="product__item product__item--color-1 card">

        <div class="">
          <div class="product__img-holder">
            <%= image_tag @site.preview.url, style: 'height: 491px' %>
          </div>
        </div>

        <div class="product__content card__content">

          <header class="product__header">
            <div class="product__header-inner">
              <span class="product__category"> <%= @site.category.title %> </span>
              <h2 class="product__title" style="margin-bottom: 2%;"> <%= @site.title %> </h2>
              <span class="product__category"> <%= link_to 'visit', @site.link, style: 'margin-left: 2%;text-decoration: underline', target: '_blank' %> </span>
              <div class="product__ratings">
                <% 
                  @count = 5 - @result 
                  @temp = 1
                %>
                <% @result.times do %>
                  <%= link_to '', '', class: 'fa fa-star ' %>
                  <% @temp = @temp + 1 %>
                <% end %>
                
                <% @count.times do %>
                  <%= link_to '', '', class: 'fa fa-star empty' %>
                  <% @temp = @temp + 1 %>
                <% end %>
              </div>
            </div>
          </header>

          <div class="product__excerpt">
            <h6>Description</h6>
            <%= truncate(@site.description, length: 90) %>
          </div>

          <% if user_signed_in? %>
            <form action="#" class="product__params">
              <div class="product__param-item product__param-item--color">
                <label>Trust</label>
                <div class="product__ratings">
                  <% 
                    @count = 5 - @trust_rating 
                    @temp = 1
                  %>
                  <% @trust_rating.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'trust', star: @temp), class: 'fa fa-star ' %>
                    <% @temp = @temp + 1 %>
                  <% end %>
                  
                  <% @count.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'trust', star: @temp), class: 'fa fa-star empty' %>
                    <% @temp = @temp + 1 %>
                  <% end %>
                </div>
              </div>
              <div class="product__param-item product__param-item--size">
                <label class="control-label" for="select-size">Performance</label>
                <div class="product__ratings">
                  <% 
                    @count = 5 - @performance_rating 
                    @temp = 1
                  %>
                  <% @performance_rating.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'performance', star: @temp), class: 'fa fa-star ' %>
                    <% @temp = @temp + 1 %>
                  <% end %>
                  
                  <% @count.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'performance', star: @temp), class: 'fa fa-star empty' %>
                    <% @temp = @temp + 1 %>
                  <% end %>   
                </div>
              </div>
              <div class="product__param-item product__param-item--quantity">
                <label>Features</label>
                <div class="product__ratings">
                  <% 
                    @count = 5 - @feature_rating 
                    @temp = 1
                  %>
                  <% @feature_rating.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'feature', star: @temp), class: 'fa fa-star ' %>
                    <% @temp = @temp + 1 %>
                  <% end %>
                  
                  <% @count.times do %>
                    <%= link_to '', rating_site_path(@site, type: 'feature', star: @temp), class: 'fa fa-star empty' %>
                    <% @temp = @temp + 1 %>
                  <% end %>
                </div>
              </div>
            </form>
          <% else %>
            <p> <%= link_to 'Login', new_user_session_path %> to record your ratings. </p>
          <% end %>
          <footer class="product__footer">
            <!-- <a href="#" class="btn btn-default btn-single-icon product__wish"><i class="icon-heart"></i></a> -->
          </footer>
        </div>
      </div>

    </div>
    <!-- Single Product / End -->

    <!-- Single Product Tabbed Content -->
    <div class="product-tabs card card--xlg">
    
      <!-- Nav tabs -->
      <ul class="nav nav-tabs nav-justified nav-product-tabs">
        <li role="presentation" class="active"><a href="#tab-desciption" role="tab" data-toggle="tab"><small>Site</small>Full Description</a></li>
        <li role="presentation"><a href="#tab-reviews" role="tab" data-toggle="tab"><small>Sites</small>User Reviews <span id="top-reviews-count"> (<%= @site.reviews.count %>) </span> </a></li>
      </ul>
    
      <!-- Tab panes -->
      <div class="tab-content card__content">
    
        <!-- Tab: Description -->
        <div role="tabpanel" class="tab-pane fade in active" id="tab-desciption">
        
          <header class="product-tabs__header">
            <h2>Site Full Description</h2>
          </header>
          
          <p> <%= @site.description %> </p>
          
        </div>
        <!-- Tab: Description / End -->
    
        <!-- Tab: Reviews -->
        <div class="tab-pane fade" id="tab-reviews">
    
          <section class="product-tabs__section">
          
            <header class="product-tabs__header">
              <h2> <span id="reviews-count"> <%= @site.reviews.count %> </span> User Reviews</h2>
            </header>
            
            <!-- Product Reviews -->
            <ul class="comments comments--left-thumb" id="reviews">
              <%= render @site.reviews %>
            </ul>
            <p style="color: green" id="success-note"> </p>
            <!-- Product Reviews / End -->
            <div id="myModal" class="modal fade" role="dialog"> </div>
          
          </section>
          
          <% if user_signed_in? %>
            <section class="product-tabs__section">
            
              <header class="product-tabs__header">
                <h2>Write a Review</h2>
              </header>
              
              <!-- Reviews Form -->
              <%= render 'reviews/form' %> 
              <!-- Reviews Form / End -->
              
            </section>
          <% else %>
            <section class="product-tabs__section">
              <header class="product-tabs__header">
                <h4> <%= link_to 'Login', new_user_session_path %> to make a Review</h4>
              </header>
            </section>
          <% end %>
    
        </div>
        <!-- Tab: Reviews / End -->
      </div>
    
    </div>
    <!-- Single Product Tabbed Content / End -->

  </div>
</div>

<!-- Content / End -->

<%= javascript_include_tag 'jquery/jquery.min.js', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'js/core-min.js', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'js/custom.js', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'js/init.js', 'data-turbolinks-track': 'reload' %>